/**
 * Unified Generator Service
 * Single Claude call for planning + code generation
 * Eliminates GST translation overhead for better reliability
 */

import type { GeometricStructureTree, ImageData } from '../types';
import { getAuthToken } from './apiClient';
import { getPreferencesForPrompt, loadPreferences } from './preferencesService';
import { streamClaudeResponse } from './streamingClient';

const DEFAULT_MODEL = 'claude-sonnet-4-20250514';

// Unified system prompt - combines planning and coding
const UNIFIED_SYSTEM_PROMPT = `
You are a 3D printing design engineer that generates OpenSCAD code.
You receive design requests and produce valid, printable OpenSCAD code directly.

## YOUR WORKFLOW
1. **Analyze** the request - understand what the user wants
2. **Plan** the geometry - components, dimensions, relationships
3. **Generate** clean OpenSCAD code

## WHEN TO ASK CLARIFYING QUESTIONS
ALWAYS ask 2-3 clarifying questions when:
- **Multiple distinct components** mentioned (e.g., "mount + plate + clips" = 3+ parts)
- **Attachment relationships** unclear (how parts connect to each other)
- **Overall dimensions unspecified** (plate size, total length, height)
- **Layout/arrangement ambiguous** (spacing, orientation, side placement)
- **Complex functional parts** (mounts, adapters, multi-part assemblies)

For tactical/military specs (Picatinny, MOLLE, etc.), STILL ask about:
- Overall assembly dimensions (plate size, total footprint)
- Number of attachment points (how many clips, rails, slots)
- Orientation (which side faces up/out, front/back arrangement)
- Specific use case details (plate carrier type, rail length needed)

DO NOT ask questions ONLY when:
- User provides explicit dimensions for ALL components
- User says "use defaults" or "standard dimensions"
- User is making a simple edit (e.g., "make it bigger", "add holes")
- Design is a single simple object with clear specs

## IF ASKING QUESTIONS
Output JSON:
{
  "needsClarification": true,
  "clarifications": [
    { "question": "What are the overall dimensions?", "suggestions": ["50x30x10mm", "100x60x20mm", "Custom"] }
  ]
}

## IF GENERATING (default - prefer this)
Output ONLY valid OpenSCAD code. No markdown fences, no explanations outside comments.

## CRITICAL OPENSCAD RULES

### 1. Variable Immutability (MOST COMMON ERROR)
Variables are compile-time constants. Define ALL at TOP before use.
WRONG: cube([width, height, depth]); width = 10;
RIGHT: width = 10; cube([width, height, depth]);

### 2. Epsilon for Boolean Operations
All difference() operations need epsilon overlap.
ALWAYS define: eps = 0.01;
Cutters must extend PAST surfaces: h = thickness + eps*2

### 3. Transform Order (Right-to-Left)
translate([10,0,0]) rotate([0,0,45]) cube(5);
// 1. cube created, 2. rotated 45°, 3. translated

### 4. Standard Primitives + Built-in Library
Use built-in primitives: cube, sphere, cylinder, polyhedron, linear_extrude, rotate_extrude, hull, difference, union, intersection

For tactical/military equipment, USE the built-in tactical library:
\`\`\`
use <libraries/tactical.scad>
\`\`\`
IMPORTANT:
- Use \`use <>\` NOT \`include <>\` (use imports modules only)
- NEVER redefine modules from tactical.scad - just call them
- NO external libraries (no BOSL2, MCAD, etc.)

## CODE STRUCTURE TEMPLATE
// [Model Name] - [Brief description]
// Generated by PolyGen AI

// ============ Parameters ============
param1 = value1;  // description
param2 = value2;

// ============ Settings ============
$fn = 64;  // Curve quality
eps = 0.01;  // Boolean overlap

// ============ Modules ============
module component_name() {
    // ...
}

// ============ Main Geometry ============
difference() {
    // Positive geometry
    // Negative geometry (cutouts)
}

## TACTICAL LIBRARY (use <libraries/tactical.scad>)
For tactical/military equipment, import the built-in library and use these modules.
NEVER redefine these - just call them after the use statement.

### Available Modules (signatures only):

\`\`\`
// Picatinny Rail Modules (MIL-STD-1913)
picatinny_rail(slots = 5, height = 15, with_slots = true)
  // Female receiver - dovetail groove accepts male rail
picatinny_rail_male(slots = 5, with_slots = true)
  // Male rail - dovetail ridge fits into female mount
picatinny_groove(length = 50)
  // Subtraction primitive - use in difference() to cut groove

// MOLLE Modules (TW-PL-507F)
molle_clip(width = 28, height = 40, rows = 1)
  // Hook-style clip for 25mm webbing
molle_adapter_plate(plate_width = 80, plate_height = 60, plate_thickness = 5, clip_columns = 2)
  // Complete adapter plate with integrated clips

// Combined Tactical
picatinny_molle_adapter(slots = 5, plate_width = 80, plate_height = 50, clip_columns = 2)
  // Complete Picatinny-to-MOLLE adapter

// Utility Modules
rcube(size, r = 2)              // Rounded cube
counterbore(shaft_d, shaft_depth, head_d, head_depth)  // Flush screw holes
tube(od, id, h)                 // Hollow cylinder
\`\`\`

### Example: Tactical Equipment
\`\`\`openscad
use <libraries/tactical.scad>

// Parameters
plate_width = 100;
plate_height = 60;

// Assembly
union() {
    // Base plate
    cube([plate_width, 5, plate_height], center=true);

    // Picatinny on front
    translate([0, 10, 0])
        rotate([90, 0, 0])
            picatinny_rail(slots=5, height=15);

    // MOLLE clips on back
    translate([-25, -5, 0]) molle_clip();
    translate([25, -5, 0]) molle_clip();
}
\`\`\`

## INLINE MODULES (define these yourself when needed)
For simple patterns not in the library, define inline:

### Tube/Pipe
module tube(od, id, h) {
    difference() {
        cylinder(h=h, d=od, center=true);
        cylinder(h=h + eps*2, d=id, center=true);
    }
}

### Step Hole (supports-free printing)
module step_hole(d, h, steps=3) {
    for (i = [0:steps-1]) {
        translate([0, 0, i * h/steps])
            cylinder(h=h/steps + eps, d1=d - (steps-i)*0.4, d2=d - (steps-i-1)*0.4);
    }
}

## TACTICAL EQUIPMENT ASSEMBLY RULES
When building plate carrier adapters (Picatinny + MOLLE):
1. MOLLE clips hook TOWARD the body (negative Y direction if body is at -Y)
2. Picatinny groove opens AWAY from body (positive Z or Y, opposite to MOLLE)
3. Base plate connects both - clips on INBOARD side, rail on OUTBOARD side
4. Always use these reference modules - do NOT improvise the geometry

## INDUSTRY STANDARDS (use these, don't ask)

### Fastener Clearances
- M3: 3.4mm hole, 5.5mm head
- M4: 4.5mm hole, 7mm head
- M5: 5.5mm hole, 8.5mm head

### Picatinny Rail (MIL-STD-1913)
- Top width: 21.2mm, Base: 20.6mm
- Height: 9.6mm, Slot: 5.23mm wide
- Slot spacing: 10.01mm center-to-center

### MOLLE/PALS
- Webbing: 25mm wide
- Row height: 25mm
- Slot spacing: 38mm horizontal

### 3D Printing
- Min wall: 1.2mm (3 perimeters @ 0.4mm)
- Fit clearance: 0.2mm normal, 0.4mm loose
- Overhang: max 45° without support

## MANUFACTURING CHECKLIST
Before output, verify:
[ ] All variables defined BEFORE use
[ ] eps = 0.01 defined
[ ] difference() cutters extend by eps*2
[ ] All semicolons present
[ ] All braces matched
[ ] $fn set for curves
[ ] No include/use statements
`;

// Edit system prompt
const EDIT_SYSTEM_PROMPT = `
You are an OpenSCAD code editor. Apply precise modifications to existing code.

## RULES
1. PRESERVE existing design intent and relationships between parts
2. Make MINIMAL changes - only what's requested
3. Maintain clearances - don't let parts collide
4. Variables are immutable - add new ones, don't reassign
5. Keep eps = 0.01 for boolean operations
6. NO libraries - pure OpenSCAD only

## BEFORE EDITING - ASK YOURSELF
1. What other components depend on this part?
2. Will my change cause parts to overlap?
3. Does my change preserve functional purpose?

## OUTPUT
Return COMPLETE modified SCAD file.
Output ONLY valid OpenSCAD code, no markdown.
`;

export interface UnifiedInput {
  userPrompt: string;
  imageData?: ImageData;
  existingCode?: string;
  existingGST?: GeometricStructureTree;
  conversationHistory?: string[];
  validationErrors?: string[];
  isEdit?: boolean;
  /** Streaming callback: receives each chunk and accumulated text */
  onChunk?: (chunk: string, fullText: string) => void;
  /** Enable streaming (defaults to true when onChunk is provided) */
  useStreaming?: boolean;
}

export interface UnifiedOutput {
  needsClarification: boolean;
  clarifications?: { question: string; suggestions: string[] }[];
  scadCode?: string;
  gst?: GeometricStructureTree; // Optional - extracted from code comments
}

/**
 * Call Claude API via server proxy
 */
async function callClaude(
  prompt: string,
  systemPrompt: string,
  imageData?: ImageData,
  abortSignal?: AbortSignal
): Promise<string> {
  const token = await getAuthToken();
  if (!token) {
    throw new Error('Authentication required. Please log in.');
  }

  // Build messages array
  type MessageContent =
    | { type: 'text'; text: string }
    | { type: 'image'; source: { type: 'base64'; media_type: string; data: string } };
  type Message = { role: 'user' | 'assistant'; content: string | MessageContent[] };
  const messages: Message[] = [];

  if (imageData) {
    // Multimodal message with image
    messages.push({
      role: 'user',
      content: [
        {
          type: 'image',
          source: {
            type: 'base64',
            media_type: imageData.mimeType,
            data: imageData.base64,
          },
        },
        {
          type: 'text',
          text: prompt,
        },
      ],
    });
  } else {
    messages.push({ role: 'user', content: prompt });
  }

  // Build request body with prompt caching support
  // Research: Caching system prompts reduces costs by 50%+ for multi-turn conversations
  const requestBody = {
    model: process.env.CODER_MODEL || DEFAULT_MODEL,
    max_tokens: 8192,
    // Use structured system message format for prompt caching
    // The cache_control flag tells Claude to cache this content
    system: [
      {
        type: 'text',
        text: systemPrompt,
        cache_control: { type: 'ephemeral' },
      },
    ],
    messages,
  };

  const response = await fetch('/api/claude', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(requestBody),
    signal: abortSignal,
  });

  if (!response.ok) {
    const errorBody = await response.json().catch(() => ({ error: { message: 'Unknown error' } }));
    const errorMessage =
      errorBody?.error?.message || errorBody?.error || `API error: ${response.status}`;
    console.error('Claude API error:', errorBody);
    throw new Error(typeof errorMessage === 'string' ? errorMessage : JSON.stringify(errorMessage));
  }

  const data = await response.json();
  const content = data.content?.[0];
  if (!content || content.type !== 'text') {
    throw new Error('Unexpected response format from Claude');
  }

  return content.text;
}

/**
 * Call Claude API with streaming support via SSE
 * Provides real-time feedback during 30-60s generation
 */
async function callClaudeStreaming(
  prompt: string,
  systemPrompt: string,
  imageData?: ImageData,
  onChunk?: (chunk: string, fullText: string) => void,
  abortSignal?: AbortSignal
): Promise<string> {
  // Build messages array (same as callClaude)
  type MessageContent =
    | { type: 'text'; text: string }
    | { type: 'image'; source: { type: 'base64'; media_type: string; data: string } };
  type Message = { role: 'user' | 'assistant'; content: string | MessageContent[] };
  const messages: Message[] = [];

  if (imageData) {
    // Multimodal message with image
    messages.push({
      role: 'user',
      content: [
        {
          type: 'image',
          source: {
            type: 'base64',
            media_type: imageData.mimeType,
            data: imageData.base64,
          },
        },
        {
          type: 'text',
          text: prompt,
        },
      ],
    });
  } else {
    messages.push({ role: 'user', content: prompt });
  }

  // Build request body with prompt caching support
  const requestBody = {
    model: process.env.CODER_MODEL || DEFAULT_MODEL,
    max_tokens: 8192,
    system: [
      {
        type: 'text',
        text: systemPrompt,
        cache_control: { type: 'ephemeral' },
      },
    ],
    messages,
  };

  return streamClaudeResponse(
    requestBody,
    {
      onChunk: onChunk || (() => {}),
      onComplete: () => {},
      onError: (error) => {
        throw error;
      },
    },
    abortSignal
  );
}

/**
 * Generate OpenSCAD code directly from user prompt
 * Unified pipeline - no intermediate GST translation
 */
export async function generate(
  input: UnifiedInput,
  abortSignal?: AbortSignal
): Promise<UnifiedOutput> {
  if (abortSignal?.aborted) {
    throw new DOMException('Request was aborted', 'AbortError');
  }

  // Load user preferences
  void loadPreferences();
  const prefsContext = getPreferencesForPrompt();

  // Build prompt based on mode
  let prompt: string;
  let systemPrompt: string;

  if (input.isEdit && input.existingCode) {
    // Edit mode
    systemPrompt = EDIT_SYSTEM_PROMPT;
    prompt = `## EXISTING CODE
\`\`\`openscad
${input.existingCode}
\`\`\`

## EDIT REQUEST
${input.userPrompt}

Apply the requested changes. Output the complete modified SCAD code.`;
  } else {
    // New generation
    systemPrompt = UNIFIED_SYSTEM_PROMPT;

    const contextParts: string[] = [];

    if (prefsContext) {
      contextParts.push(`## USER PREFERENCES\n${prefsContext}`);
    }

    if (input.conversationHistory?.length) {
      contextParts.push(`## CONVERSATION HISTORY\n${input.conversationHistory.join('\n')}`);
    }

    if (input.imageData) {
      contextParts.push(
        `## REFERENCE IMAGE\nAnalyze the attached image and create a 3D printable version.`
      );
    }

    if (input.validationErrors?.length) {
      contextParts.push(
        `## PREVIOUS ERRORS - FIX THESE\n${input.validationErrors.map((e) => `- ${e}`).join('\n')}`
      );
    }

    prompt = `${contextParts.join('\n\n')}

## DESIGN REQUEST
${input.userPrompt}

Generate the OpenSCAD code for this design. Output ONLY valid SCAD code unless you need clarification.`;
  }

  try {
    // Use streaming if callback provided (default behavior)
    const useStreaming = input.useStreaming !== false && !!input.onChunk;

    let text: string;
    if (useStreaming) {
      text = await callClaudeStreaming(
        prompt,
        systemPrompt,
        input.imageData,
        input.onChunk,
        abortSignal
      );
    } else {
      text = await callClaude(prompt, systemPrompt, input.imageData, abortSignal);
    }

    if (abortSignal?.aborted) {
      throw new DOMException('Request was aborted', 'AbortError');
    }

    // Check if response is a clarification request
    const trimmed = text.trim();
    if (trimmed.startsWith('{') && trimmed.includes('needsClarification')) {
      try {
        const parsed = JSON.parse(trimmed);
        if (parsed.needsClarification) {
          return {
            needsClarification: true,
            clarifications: parsed.clarifications || [],
          };
        }
      } catch {
        // Not valid JSON, treat as code
      }
    }

    // Extract clean SCAD code
    const scadCode = extractScadCode(text);

    return {
      needsClarification: false,
      scadCode,
    };
  } catch (error) {
    if (error instanceof DOMException && error.name === 'AbortError') {
      throw error;
    }
    console.error('Unified generator error:', error);
    throw new Error(
      `Generation failed: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
  }
}

/**
 * Extract clean OpenSCAD code from response
 * Handles cases where Claude outputs explanation before/after code blocks
 */
function extractScadCode(text: string): string {
  const trimmed = text.trim();

  // First, try to find a code block anywhere in the text
  // This handles cases where Claude outputs explanation before the code
  const codeBlockMatch = trimmed.match(/```(?:openscad|scad)?\s*\n([\s\S]*?)```/);
  if (codeBlockMatch && codeBlockMatch[1]) {
    const extracted = codeBlockMatch[1].trim();
    // Verify it looks like OpenSCAD (has variables or primitives)
    if (extracted.match(/(?:cube|cylinder|sphere|difference|union|module|=\s*\d)/)) {
      console.log('Extracted OpenSCAD code from markdown block');
      return extracted;
    }
  }

  // Fallback: Remove markdown code fences if at start/end (legacy behavior)
  let code = trimmed;
  if (code.startsWith('```openscad')) {
    code = code.slice(12);
  } else if (code.startsWith('```scad')) {
    code = code.slice(7);
  } else if (code.startsWith('```')) {
    code = code.slice(3);
  }

  if (code.endsWith('```')) {
    code = code.slice(0, -3);
  }

  // Check if the result looks like explanation text (not OpenSCAD code)
  // If it starts with conversational text, try to find where code begins
  const codeStart = code.trim();
  if (codeStart && !codeStart.startsWith('//') && !codeStart.match(/^[$\w]+\s*=/)) {
    // Text doesn't look like OpenSCAD - might have explanation at start
    // Try to find where the actual code begins (line starting with // or variable assignment)
    const lines = codeStart.split('\n');
    const codeStartIdx = lines.findIndex(
      (line) =>
        line.trim().startsWith('//') ||
        line.trim().match(/^[$\w]+\s*=/) ||
        line.trim().match(/^(?:module|function|difference|union|cube|cylinder|sphere)\s*[({]?/)
    );
    if (codeStartIdx > 0) {
      console.warn(`Stripped ${codeStartIdx} lines of explanation text from Claude response`);
      return lines.slice(codeStartIdx).join('\n').trim();
    }
  }

  return code.trim();
}

// Export as object
export const unifiedGeneratorService = {
  generate,
};

export default unifiedGeneratorService;
