/**
 * Unified Generator Service
 * Single Claude call for planning + code generation
 * Eliminates GST translation overhead for better reliability
 */

import type { GeometricStructureTree, ImageData } from '../types';
import { getAuthToken } from './apiClient';
import { loadPreferences, getPreferencesForPrompt } from './preferencesService';
import { streamClaudeResponse } from './streamingClient';

const DEFAULT_MODEL = 'claude-sonnet-4-20250514';

// Unified system prompt - combines planning and coding
const UNIFIED_SYSTEM_PROMPT = `
You are a 3D printing design engineer that generates OpenSCAD code.
You receive design requests and produce valid, printable OpenSCAD code directly.

## YOUR WORKFLOW
1. **Analyze** the request - understand what the user wants
2. **Plan** the geometry - components, dimensions, relationships
3. **Generate** clean OpenSCAD code

## WHEN TO ASK CLARIFYING QUESTIONS
Ask 1-2 clarifying questions ONLY when:
- Critical dimensions are unspecified AND cannot be reasonably assumed
- The attachment method is unclear AND affects the design fundamentally
- Multiple interpretations exist that would result in very different designs

DO NOT ask questions when:
- User provides specific dimensions
- Standard industry specs apply (see below)
- User is iterating on existing design
- A reasonable default exists

## IF ASKING QUESTIONS
Output JSON:
{
  "needsClarification": true,
  "clarifications": [
    { "question": "What are the overall dimensions?", "suggestions": ["50x30x10mm", "100x60x20mm", "Custom"] }
  ]
}

## IF GENERATING (default - prefer this)
Output ONLY valid OpenSCAD code. No markdown fences, no explanations outside comments.

## CRITICAL OPENSCAD RULES

### 1. Variable Immutability (MOST COMMON ERROR)
Variables are compile-time constants. Define ALL at TOP before use.
WRONG: cube([width, height, depth]); width = 10;
RIGHT: width = 10; cube([width, height, depth]);

### 2. Epsilon for Boolean Operations
All difference() operations need epsilon overlap.
ALWAYS define: eps = 0.01;
Cutters must extend PAST surfaces: h = thickness + eps*2

### 3. Transform Order (Right-to-Left)
translate([10,0,0]) rotate([0,0,45]) cube(5);
// 1. cube created, 2. rotated 45°, 3. translated

### 4. Standard Primitives Only
NO libraries (no BOSL2, MCAD, include, use statements)
Use: cube, sphere, cylinder, polyhedron, linear_extrude, rotate_extrude, hull, difference, union, intersection

## CODE STRUCTURE TEMPLATE
// [Model Name] - [Brief description]
// Generated by PolyGen AI

// ============ Parameters ============
param1 = value1;  // description
param2 = value2;

// ============ Settings ============
$fn = 64;  // Curve quality
eps = 0.01;  // Boolean overlap

// ============ Modules ============
module component_name() {
    // ...
}

// ============ Main Geometry ============
difference() {
    // Positive geometry
    // Negative geometry (cutouts)
}

## COMMON PATTERNS

### Rounded Cuboid
module rcube(size, r) {
    hull() {
        for (x = [-1, 1], y = [-1, 1], z = [-1, 1]) {
            translate([x*(size[0]/2-r), y*(size[1]/2-r), z*(size[2]/2-r)])
                sphere(r=r, $fn=32);
        }
    }
}

### Tube/Pipe
module tube(od, id, h) {
    difference() {
        cylinder(h=h, d=od, center=true);
        cylinder(h=h + eps*2, d=id, center=true);
    }
}

### Counterbore Hole
module counterbore(shaft_d, shaft_depth, head_d, head_depth) {
    union() {
        cylinder(h=shaft_depth + eps, d=shaft_d);
        translate([0, 0, shaft_depth - head_depth])
            cylinder(h=head_depth + eps, d=head_d);
    }
}

## INDUSTRY STANDARDS (use these, don't ask)

### Fastener Clearances
- M3: 3.4mm hole, 5.5mm head
- M4: 4.5mm hole, 7mm head
- M5: 5.5mm hole, 8.5mm head

### Picatinny Rail (MIL-STD-1913)
- Top width: 21.2mm, Base: 20.6mm
- Height: 9.6mm, Slot: 5.23mm wide
- Slot spacing: 10.01mm center-to-center

### MOLLE/PALS
- Webbing: 25mm wide
- Row height: 25mm
- Slot spacing: 38mm horizontal

### 3D Printing
- Min wall: 1.2mm (3 perimeters @ 0.4mm)
- Fit clearance: 0.2mm normal, 0.4mm loose
- Overhang: max 45° without support

## MANUFACTURING CHECKLIST
Before output, verify:
[ ] All variables defined BEFORE use
[ ] eps = 0.01 defined
[ ] difference() cutters extend by eps*2
[ ] All semicolons present
[ ] All braces matched
[ ] $fn set for curves
[ ] No include/use statements
`;

// Edit system prompt
const EDIT_SYSTEM_PROMPT = `
You are an OpenSCAD code editor. Apply precise modifications to existing code.

## RULES
1. PRESERVE existing design intent and relationships between parts
2. Make MINIMAL changes - only what's requested
3. Maintain clearances - don't let parts collide
4. Variables are immutable - add new ones, don't reassign
5. Keep eps = 0.01 for boolean operations
6. NO libraries - pure OpenSCAD only

## BEFORE EDITING - ASK YOURSELF
1. What other components depend on this part?
2. Will my change cause parts to overlap?
3. Does my change preserve functional purpose?

## OUTPUT
Return COMPLETE modified SCAD file.
Output ONLY valid OpenSCAD code, no markdown.
`;

export interface UnifiedInput {
  userPrompt: string;
  imageData?: ImageData;
  existingCode?: string;
  existingGST?: GeometricStructureTree;
  conversationHistory?: string[];
  validationErrors?: string[];
  isEdit?: boolean;
  /** Streaming callback: receives each chunk and accumulated text */
  onChunk?: (chunk: string, fullText: string) => void;
  /** Enable streaming (defaults to true when onChunk is provided) */
  useStreaming?: boolean;
}

export interface UnifiedOutput {
  needsClarification: boolean;
  clarifications?: { question: string; suggestions: string[] }[];
  scadCode?: string;
  gst?: GeometricStructureTree; // Optional - extracted from code comments
}

/**
 * Call Claude API via server proxy
 */
async function callClaude(
  prompt: string,
  systemPrompt: string,
  imageData?: ImageData,
  abortSignal?: AbortSignal
): Promise<string> {
  const token = await getAuthToken();
  if (!token) {
    throw new Error('Authentication required. Please log in.');
  }

  // Build messages array
  type MessageContent =
    | { type: 'text'; text: string }
    | { type: 'image'; source: { type: 'base64'; media_type: string; data: string } };
  type Message = { role: 'user' | 'assistant'; content: string | MessageContent[] };
  const messages: Message[] = [];

  if (imageData) {
    // Multimodal message with image
    messages.push({
      role: 'user',
      content: [
        {
          type: 'image',
          source: {
            type: 'base64',
            media_type: imageData.mimeType,
            data: imageData.base64,
          },
        },
        {
          type: 'text',
          text: prompt,
        },
      ],
    });
  } else {
    messages.push({ role: 'user', content: prompt });
  }

  // Build request body with prompt caching support
  // Research: Caching system prompts reduces costs by 50%+ for multi-turn conversations
  const requestBody = {
    model: process.env.CODER_MODEL || DEFAULT_MODEL,
    max_tokens: 8192,
    // Use structured system message format for prompt caching
    // The cache_control flag tells Claude to cache this content
    system: [
      {
        type: 'text',
        text: systemPrompt,
        cache_control: { type: 'ephemeral' },
      },
    ],
    messages,
  };

  const response = await fetch('/api/claude', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(requestBody),
    signal: abortSignal,
  });

  if (!response.ok) {
    const errorBody = await response.json().catch(() => ({ error: { message: 'Unknown error' } }));
    const errorMessage =
      errorBody?.error?.message || errorBody?.error || `API error: ${response.status}`;
    console.error('Claude API error:', errorBody);
    throw new Error(typeof errorMessage === 'string' ? errorMessage : JSON.stringify(errorMessage));
  }

  const data = await response.json();
  const content = data.content?.[0];
  if (!content || content.type !== 'text') {
    throw new Error('Unexpected response format from Claude');
  }

  return content.text;
}

/**
 * Call Claude API with streaming support via SSE
 * Provides real-time feedback during 30-60s generation
 */
async function callClaudeStreaming(
  prompt: string,
  systemPrompt: string,
  imageData?: ImageData,
  onChunk?: (chunk: string, fullText: string) => void,
  abortSignal?: AbortSignal
): Promise<string> {
  // Build messages array (same as callClaude)
  type MessageContent =
    | { type: 'text'; text: string }
    | { type: 'image'; source: { type: 'base64'; media_type: string; data: string } };
  type Message = { role: 'user' | 'assistant'; content: string | MessageContent[] };
  const messages: Message[] = [];

  if (imageData) {
    // Multimodal message with image
    messages.push({
      role: 'user',
      content: [
        {
          type: 'image',
          source: {
            type: 'base64',
            media_type: imageData.mimeType,
            data: imageData.base64,
          },
        },
        {
          type: 'text',
          text: prompt,
        },
      ],
    });
  } else {
    messages.push({ role: 'user', content: prompt });
  }

  // Build request body with prompt caching support
  const requestBody = {
    model: process.env.CODER_MODEL || DEFAULT_MODEL,
    max_tokens: 8192,
    system: [
      {
        type: 'text',
        text: systemPrompt,
        cache_control: { type: 'ephemeral' },
      },
    ],
    messages,
  };

  return streamClaudeResponse(
    requestBody,
    {
      onChunk: onChunk || (() => {}),
      onComplete: () => {},
      onError: (error) => {
        throw error;
      },
    },
    abortSignal
  );
}

/**
 * Generate OpenSCAD code directly from user prompt
 * Unified pipeline - no intermediate GST translation
 */
export async function generate(
  input: UnifiedInput,
  abortSignal?: AbortSignal
): Promise<UnifiedOutput> {
  if (abortSignal?.aborted) {
    throw new DOMException('Request was aborted', 'AbortError');
  }

  // Load user preferences
  void loadPreferences();
  const prefsContext = getPreferencesForPrompt();

  // Build prompt based on mode
  let prompt: string;
  let systemPrompt: string;

  if (input.isEdit && input.existingCode) {
    // Edit mode
    systemPrompt = EDIT_SYSTEM_PROMPT;
    prompt = `## EXISTING CODE
\`\`\`openscad
${input.existingCode}
\`\`\`

## EDIT REQUEST
${input.userPrompt}

Apply the requested changes. Output the complete modified SCAD code.`;
  } else {
    // New generation
    systemPrompt = UNIFIED_SYSTEM_PROMPT;

    const contextParts: string[] = [];

    if (prefsContext) {
      contextParts.push(`## USER PREFERENCES\n${prefsContext}`);
    }

    if (input.conversationHistory?.length) {
      contextParts.push(`## CONVERSATION HISTORY\n${input.conversationHistory.join('\n')}`);
    }

    if (input.imageData) {
      contextParts.push(
        `## REFERENCE IMAGE\nAnalyze the attached image and create a 3D printable version.`
      );
    }

    if (input.validationErrors?.length) {
      contextParts.push(
        `## PREVIOUS ERRORS - FIX THESE\n${input.validationErrors.map((e) => `- ${e}`).join('\n')}`
      );
    }

    prompt = `${contextParts.join('\n\n')}

## DESIGN REQUEST
${input.userPrompt}

Generate the OpenSCAD code for this design. Output ONLY valid SCAD code unless you need clarification.`;
  }

  try {
    // Use streaming if callback provided (default behavior)
    const useStreaming = input.useStreaming !== false && !!input.onChunk;

    let text: string;
    if (useStreaming) {
      text = await callClaudeStreaming(
        prompt,
        systemPrompt,
        input.imageData,
        input.onChunk,
        abortSignal
      );
    } else {
      text = await callClaude(prompt, systemPrompt, input.imageData, abortSignal);
    }

    if (abortSignal?.aborted) {
      throw new DOMException('Request was aborted', 'AbortError');
    }

    // Check if response is a clarification request
    const trimmed = text.trim();
    if (trimmed.startsWith('{') && trimmed.includes('needsClarification')) {
      try {
        const parsed = JSON.parse(trimmed);
        if (parsed.needsClarification) {
          return {
            needsClarification: true,
            clarifications: parsed.clarifications || [],
          };
        }
      } catch {
        // Not valid JSON, treat as code
      }
    }

    // Extract clean SCAD code
    const scadCode = extractScadCode(text);

    return {
      needsClarification: false,
      scadCode,
    };
  } catch (error) {
    if (error instanceof DOMException && error.name === 'AbortError') {
      throw error;
    }
    console.error('Unified generator error:', error);
    throw new Error(
      `Generation failed: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
  }
}

/**
 * Extract clean OpenSCAD code from response
 */
function extractScadCode(text: string): string {
  let code = text.trim();

  // Remove markdown code fences
  if (code.startsWith('```openscad')) {
    code = code.slice(12);
  } else if (code.startsWith('```scad')) {
    code = code.slice(7);
  } else if (code.startsWith('```')) {
    code = code.slice(3);
  }

  if (code.endsWith('```')) {
    code = code.slice(0, -3);
  }

  return code.trim();
}

// Export as object
export const unifiedGeneratorService = {
  generate,
};

export default unifiedGeneratorService;
